#ifndef AQUARIUMSETTINGS_H
#define AQUARIUMSETTINGS_H

//GENERAL SETTINGS
#define PHYSICS_SCALE 100

#define NUM_FISH_START 20
#define NUM_FISH_IDEAL 20
#define NUM_PLANTS 3
#define NUM_ATTRACTORS 2
#define PHYSICS_SCALE 50

#define BORDER_BUFFER 0

//WATER SETTINGS

//AGE THRESHOLDS
#define AGE_EGG 0.1
#define AGE_CHILD 0.3
#define AGE_TEEN 0.5
#define AGE_ADULT 0.7
#define AGE_SENIOR 0.9
#define AGE_DEAD 1.0

//GENERAL FORCE SETTINGS
#define MAX_FORCE 3
#define FOOD_FORCE MAX_FORCE * 2
#define BOUNDARY_FORCE 2  //change to 0.2

//EGG SETTINGS
#define EGG_SIZE 1
#define EGG_COLOR 200, 200, 200

//FISH SETTINGS
#define FISH_NUM_SEGMENTS 4, 8
#define FISH_MIN_SEGMENT_SIZE 2.0
#define FISH_MAX_SEGMENT_SIZE 2, 6
#define FISH_GAP_BETWEEN_SEGMENTS 70, 100

#define FISH_MAX_SPEED 30
#define FISH_MIN_SPEED 10
#define FISH_MAX_FORCE 0.3
#define FISH_SIN_AMPLITUDE 2
#define FISH_SIN_FREQUENCY 0.002
#define FISH_NOISE_AMPLITUDE 6
#define FISH_NOISE_FREQUENCY 0.01

//SNAKE SETTINGS
#define SNAKE_NUM_SEGMENTS 8, 32

//STAR SETTINGS
#define STAR_LENGTH 4, 6
#define STAR_RAD 2,4
#define STAR_NUM_ARMS 5, 10

//TURTLE SETTINGS
#define TURTLE_LENGTH 4, 8
#define TURTLE_WIDTH 2, 4


//CHILD SETTINGS
#define CHILD_COLOR 255, 255, 255

//TEEN SETTINGS

//ADULT SETTINGS

//SENIOR SETTINGS
#define SENIOR_COLOR 0, 0, 0

//FLOCKING SETTINGS
#define FLOCK_MAX_FORCE 0.8
#define SEPARATION_DISTANCE 20
#define ALIGNMENT_DISTANCE 30
#define COHESION_DISTANCE 30
#define SEPARATION_WEIGHT .3
#define ALIGNMENT_WEIGHT 1.0
#define COHESION_WEIGHT .2

//ATTRACTOR SETTINGS
#define ATTRACTOR_MAX_SPEED 50
#define ATTRACTOR_MIN_SPEED 30
#define ATTRACTOR_SIN_AMPLITUDE 5
#define ATTRACTOR_SIN_FREQUENCY 0.002
#define ATTRACTOR_NOISE_AMPLITUDE 6
#define ATTRACTOR_NOISE_FREQUENCY 0.01


#endif