#pragma once

#define FIRMWARE_VERSION_MAJOR 2
#define FIRMWARE_VERSION_MINOR 0
#define FIRMWARE_VERSION_PATCH 0

// #define PANEL_UPCYCLED 1

#define RUN_DEMO 1

#define AQUARIUM_ENABLED 1
#define SCD40_ENABLED 1
#define ADXL345_ENABLED 1
#define BH1750_ENABLED 1
#define TOUCH_ENABLED 1

#define WIFI_ENABLED 1

#define STATE_SAVE_INTERVAL 30  //in minutes
#define MATRIX_REFRESH_INTERVAL 300000  //in ms